### ISSUE TITLE
Genauigkeit der Inzidenzwerte

### ISSUE THREAD

**Issue by jbracher** [robert-koch-institut/SARI-Hospitalisierungsinzidenz#1]
Guten Tag,

erst einmal vielen Dank, dass diese Daten auf GitHub verfügbar gemacht werden!

Ich hätte eine Frage zur Datengenauigkeit: Aktuell sind die Daten nur als ganze Zahlen ausgeschrieben. Da die Werte ja nicht als rohe Zählwerte sondern pro 100.000 Bevölkerung ausgegeben werden wollte ich mich erkundigen, ob sie vielleicht mit einer Nachkommastelle angegeben werden könnten. In den mittleren Altersgruppen sind die Werte oft im niedrigen einstelligen Bereich, da wäre es mit einer Nachkommastelle informativer.

Beste Grüße, Johannes Bracher

**Comment by RKIOpenData** [comment]
Hallo Johannes,

bitte entschuldige, dass wir uns erst jetzt melden. Das Issue ist wohl bei uns untergegangen. Aber wir haben deinen Feature Request gehört und haben von unseren Fachabteilungen schon die Zusage, dass wir zukünftig die Inzidenzwerte mit einer Nachkommastelle bereitstellen können.

Ich hoffe wir sind ab der nächsten Woche schon so weit, das wir die Daten so bereitstellen können.

viele Grüße
Knut
für das Team RKI | Open Data

**Comment by jbracher** [comment]
Hallo Knut,

vielen Dank für die Rückmldung (und danke an die Fachabteilungen, dass das so unkompliziert ermöglicht werden kann). Wir freuen uns auf die neuen Daten, ob nun diese oder in einer der folgenden Wochen.

Beste Grüße, Johannes

**Comment by jbracher** [comment]
Hallo Knut @RKIOpenData,

ich wollte noch einmal nachfragen, ob es mit der Umstellung Schwierigkeiten gibt. Es ist nicht so, dass das für uns riesige Eile hätte, aber es wäre super, wenn es das im Lauf der nächsten Wochen geben würde. Vielen Dank für eure Arbeit!

Johannes

**Comment by jbracher** [comment]
Hallo noch einmal, ich habe gerade gesehen, dass die neuste Datei die Nachkommastellen enthält. Vielen Dank dafür!

**Comment by HannesWuensche** [comment]
Hallo @jbracher,

danke der Nachfrage und des Erinnerns. 

Beste Grüße
@HannesWuensche
